pub static COUNTRY_CODES: [(&str, &str, &str, &str, &str, &str); 246] = [
    (
        "+93",
        "\u{1F1E6}\u{1F1EB}",
        "+93 ...-....",
        "Afghanistan",
        "Asia",
        "Southern Asia",
    ),
    (
        "+355",
        "\u{1F1E6}\u{1F1F1}",
        "+355 ... ....",
        "Albania",
        "Europe",
        "Southern Europe",
    ),
    (
        "+213",
        "\u{1F1E9}\u{1F1FF}",
        "+213 ... .. ..",
        "Algeria",
        "Africa",
        "Northern Africa",
    ),
    (
        "+376",
        "\u{1F1E6}\u{1F1E9}",
        "+376 ... ...",
        "Andorra",
        "Europe",
        "Southern Europe",
    ),
    (
        "+244",
        "\u{1F1E6}\u{1F1F4}",
        "+244 ... ....",
        "Angola",
        "Africa",
        "Middle Africa",
    ),
    (
        "+1264",
        "\u{1F1E6}\u{1F1EE}",
        "+1264 ... ....",
        "Anguilla",
        "America",
        "Caribbean",
    ),
    (
        "+1268",
        "\u{1F1E6}\u{1F1EC}",
        "+1268 ... ....",
        "Antigua and Barbuda",
        "America",
        "Caribbean",
    ),
    (
        "+54",
        "\u{1F1E6}\u{1F1F7}",
        "+54 ... .......",
        "Argentina",
        "America",
        "South America",
    ),
    (
        "+374",
        "\u{1F1E6}\u{1F1F2}",
        "+374 ... ....",
        "Armenia",
        "Asia",
        "Western Asia",
    ),
    (
        "+297",
        "\u{1F1E6}\u{1F1FC}",
        "+297 ... ....",
        "Aruba",
        "America",
        "Caribbean",
    ),
    (
        "+247",
        "\u{1F1E6}\u{1F1F8}",
        "+247 ...-....",
        "Ascension Island",
        "Africa",
        "Atlantic",
    ),
    (
        "+61",
        "\u{1F1E6}\u{1F1FA}",
        "+61 .. ... ...",
        "Australia",
        "Oceania",
        "Australia",
    ),
    (
        "+672",
        "\u{1F1E6}\u{1F1FA}",
        "+672 .. ... ...",
        "Australian External Territories",
        "Oceania",
        "Australia",
    ),
    (
        "+43",
        "\u{1F1E6}\u{1F1F9}",
        "+43 ... .......",
        "Austria",
        "Europe",
        "Western Europe",
    ),
    (
        "+994",
        "\u{1F1E6}\u{1F1FF}",
        "+994 ... .. ..",
        "Azerbaijan",
        "Asia",
        "Western Asia",
    ),
    (
        "+1242",
        "\u{1F1E7}\u{1F1F8}",
        "+1242 ... ....",
        "Bahamas",
        "America",
        "Caribbean",
    ),
    (
        "+973",
        "\u{1F1E7}\u{1F1ED}",
        "+973 ... ....",
        "Bahrain",
        "Asia",
        "Western Asia",
    ),
    (
        "+880",
        "\u{1F1E7}\u{1F1E9}",
        "+880 ...-.....",
        "Bangladesh",
        "Asia",
        "Southern Asia",
    ),
    (
        "+1246",
        "\u{1F1E7}\u{1F1E7}",
        "+1246 ... ....",
        "Barbados",
        "America",
        "Caribbean",
    ),
    (
        "+375",
        "\u{1F1E7}\u{1F1FE}",
        "+375 ... ....",
        "Belarus",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+32",
        "\u{1F1E7}\u{1F1EA}",
        "+32 .. ... ..",
        "Belgium",
        "Europe",
        "Western Europe",
    ),
    (
        "+501",
        "\u{1F1E7}\u{1F1FF}",
        "+501 ...-....",
        "Belize",
        "America",
        "Central America",
    ),
    (
        "+229",
        "\u{1F1E7}\u{1F1EF}",
        "+229 ... ....",
        "Benin",
        "Africa",
        "Western Africa",
    ),
    (
        "+1441",
        "\u{1F1E7}\u{1F1F2}",
        "+1441 ... ....",
        "Bermuda",
        "America",
        "Northern America",
    ),
    (
        "+975",
        "\u{1F1E7}\u{1F1F9}",
        "+975 ... ....",
        "Bhutan",
        "Asia",
        "Southern Asia",
    ),
    (
        "+591",
        "\u{1F1E7}\u{1F1F4}",
        "+591 ... ....",
        "Bolivia",
        "America",
        "South America",
    ),
    (
        "+599",
        "\u{1F1E7}\u{1F1F6}",
        "+599 ... ....",
        "Bonaire",
        "America",
        "Caribbean",
    ),
    (
        "+387",
        "\u{1F1E7}\u{1F1E6}",
        "+387 ... ....",
        "Bosnia and Herzegovina",
        "Europe",
        "Southern Europe",
    ),
    (
        "+267",
        "\u{1F1E7}\u{1F1FC}",
        "+267 ... ....",
        "Botswana",
        "Africa",
        "Southern Africa",
    ),
    (
        "+55",
        "\u{1F1E7}\u{1F1F7}",
        "+55 .. .......",
        "Brazil",
        "America",
        "South America",
    ),
    (
        "+246",
        "\u{1F1EE}\u{1F1F4}",
        "+246 ...-....",
        "British Indian Ocean Territory",
        "Africa",
        "Indian Ocean",
    ),
    (
        "+1284",
        "\u{1F1FB}\u{1F1EC}",
        "+1284 ... ....",
        "British Virgin Islands",
        "America",
        "Caribbean",
    ),
    (
        "+673",
        "\u{1F1E7}\u{1F1F3}",
        "+673 ... ....",
        "Brunei",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+359",
        "\u{1F1E7}\u{1F1EC}",
        "+359 ... ....",
        "Bulgaria",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+226",
        "\u{1F1E7}\u{1F1EB}",
        "+226 ... ....",
        "Burkina Faso",
        "Africa",
        "Western Africa",
    ),
    (
        "+257",
        "\u{1F1E7}\u{1F1EE}",
        "+257 ... ....",
        "Burundi",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+855",
        "\u{1F1F0}\u{1F1ED}",
        "+855 ...-....",
        "Cambodia",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+237",
        "\u{1F1E8}\u{1F1F2}",
        "+237 ... .. ..",
        "Cameroon",
        "Africa",
        "Middle Africa",
    ),
    (
        "+1",
        "\u{1F1E8}\u{1F1E6}",
        "+1 ... ... ....",
        "Canada",
        "America",
        "Northern America",
    ),
    (
        "+238",
        "\u{1F1E8}\u{1F1FB}",
        "+238 ... ....",
        "Cape Verde",
        "Africa",
        "Western Africa",
    ),
    (
        "+599",
        "\u{1F1E7}\u{1F1F6}",
        "+599 ... ....",
        "Caribbean Netherlands",
        "America",
        "Caribbean",
    ),
    (
        "+1345",
        "\u{1F1F0}\u{1F1FE}",
        "+1345 ... ....",
        "Cayman Islands",
        "America",
        "Caribbean",
    ),
    (
        "+236",
        "\u{1F1E8}\u{1F1EB}",
        "+236 ... .. ..",
        "Central African Republic",
        "Africa",
        "Middle Africa",
    ),
    (
        "+235",
        "\u{1F1F9}\u{1F1E9}",
        "+235 ... ....",
        "Chad",
        "Africa",
        "Middle Africa",
    ),
    (
        "+56",
        "\u{1F1E8}\u{1F1F1}",
        "+56 ... .......",
        "Chile",
        "America",
        "South America",
    ),
    (
        "+86",
        "\u{1F1E8}\u{1F1F3}",
        "+86 .. .... ....",
        "China",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+61",
        "\u{1F1E8}\u{1F1FD}",
        "+61 .. ... ...",
        "Christmas Island",
        "Oceania",
        "Australia",
    ),
    (
        "+61",
        "\u{1F1E8}\u{1F1E8}",
        "+61 .. ... ...",
        "Cocos Islands",
        "Oceania",
        "Australia",
    ),
    (
        "+57",
        "\u{1F1E8}\u{1F1F4}",
        "+57 ... .......",
        "Colombia",
        "America",
        "South America",
    ),
    (
        "+269",
        "\u{1F1F0}\u{1F1F2}",
        "+269 ... ....",
        "Comoros",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+242",
        "\u{1F1E8}\u{1F1EC}",
        "+242 ... .. ..",
        "Congo",
        "Africa",
        "Middle Africa",
    ),
    (
        "+243",
        "\u{1F1E8}\u{1F1E9}",
        "+243 ... ......",
        "Congo (DRC)",
        "Africa",
        "Middle Africa",
    ),
    (
        "+682",
        "\u{1F1E8}\u{1F1F0}",
        "+682 ... ....",
        "Cook Islands",
        "Oceania",
        "Polynesia",
    ),
    (
        "+506",
        "\u{1F1E8}\u{1F1F7}",
        "+506 ... ....",
        "Costa Rica",
        "America",
        "Central America",
    ),
    (
        "+225",
        "\u{1F1E8}\u{1F1EE}",
        "+225 ... .. ..",
        "C\u{F4}te d'Ivoire",
        "Africa",
        "Western Africa",
    ),
    (
        "+385",
        "\u{1F1ED}\u{1F1F7}",
        "+385 ... ....",
        "Croatia",
        "Europe",
        "Southern Europe",
    ),
    (
        "+53",
        "\u{1F1E8}\u{1F1FA}",
        "+53 ... .......",
        "Cuba",
        "America",
        "Caribbean",
    ),
    (
        "+599",
        "\u{1F1E7}\u{1F1F6}",
        "+599 ... ....",
        "Cura\u{E7}ao",
        "America",
        "Caribbean",
    ),
    (
        "+357",
        "\u{1F1E8}\u{1F1FE}",
        "+357 ... ....",
        "Cyprus",
        "Asia",
        "Western Asia",
    ),
    (
        "+420",
        "\u{1F1E8}\u{1F1FF}",
        "+420 ... ....",
        "Czech Republic",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+45",
        "\u{1F1E9}\u{1F1F0}",
        "+45 .. .. .. ..",
        "Denmark",
        "Europe",
        "Northern Europe",
    ),
    (
        "+246",
        "\u{1F1E9}\u{1F1EC}",
        "+246 ... ....",
        "Diego Garcia",
        "Africa",
        "Indian Ocean",
    ),
    (
        "+253",
        "\u{1F1E9}\u{1F1EF}",
        "+253 ... ....",
        "Djibouti",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+1767",
        "\u{1F1E9}\u{1F1F2}",
        "+1767 ... ....",
        "Dominica",
        "America",
        "Caribbean",
    ),
    (
        "+1",
        "\u{1F1E9}\u{1F1F4}",
        "+1 ... ... ....",
        "Dominican Republic",
        "America",
        "Caribbean",
    ),
    (
        "+593",
        "\u{1F1EA}\u{1F1E8}",
        "+593 ... ....",
        "Ecuador",
        "America",
        "South America",
    ),
    (
        "+20",
        "\u{1F1EA}\u{1F1EC}",
        "+20 ... .......",
        "Egypt",
        "Africa",
        "Northern Africa",
    ),
    (
        "+503",
        "\u{1F1F8}\u{1F1FB}",
        "+503 ... ....",
        "El Salvador",
        "America",
        "Central America",
    ),
    (
        "+240",
        "\u{1F1EC}\u{1F1F6}",
        "+240 ... ....",
        "Equatorial Guinea",
        "Africa",
        "Middle Africa",
    ),
    (
        "+291",
        "\u{1F1EA}\u{1F1F7}",
        "+291 ... ....",
        "Eritrea",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+372",
        "\u{1F1EA}\u{1F1EA}",
        "+372 ... ....",
        "Estonia",
        "Europe",
        "Northern Europe",
    ),
    (
        "+251",
        "\u{1F1EA}\u{1F1F9}",
        "+251 ... ....",
        "Ethiopia",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+500",
        "\u{1F1EB}\u{1F1F0}",
        "+500 ... ....",
        "Falkland Islands",
        "America",
        "South America",
    ),
    (
        "+298",
        "\u{1F1EB}\u{1F1F4}",
        "+298 ... ....",
        "Faroe Islands",
        "Europe",
        "Northern Europe",
    ),
    (
        "+679",
        "\u{1F1EB}\u{1F1EF}",
        "+679 ... ....",
        "Fiji",
        "Oceania",
        "Melanesia",
    ),
    (
        "+358",
        "\u{1F1EB}\u{1F1EE}",
        "+358 ... .. ..",
        "Finland",
        "Europe",
        "Northern Europe",
    ),
    (
        "+33",
        "\u{1F1EB}\u{1F1F7}",
        "+33 .. .. .. ..",
        "France",
        "Europe",
        "Western Europe",
    ),
    (
        "+596",
        "\u{1F1F2}\u{1F1EB}",
        "+596 ... ....",
        "French Antilles",
        "America",
        "Caribbean",
    ),
    (
        "+594",
        "\u{1F1EC}\u{1F1EB}",
        "+594 ... ....",
        "French Guiana",
        "America",
        "South America",
    ),
    (
        "+689",
        "\u{1F1F5}\u{1F1EB}",
        "+689 ... ....",
        "French Polynesia",
        "Oceania",
        "Polynesia",
    ),
    (
        "+241",
        "\u{1F1EC}\u{1F1E6}",
        "+241 ... ....",
        "Gabon",
        "Africa",
        "Middle Africa",
    ),
    (
        "+220",
        "\u{1F1EC}\u{1F1F2}",
        "+220 ... ....",
        "Gambia",
        "Africa",
        "Western Africa",
    ),
    (
        "+995",
        "\u{1F1EC}\u{1F1EA}",
        "+995 ... ....",
        "Georgia",
        "Asia",
        "Western Asia",
    ),
    (
        "+49",
        "\u{1F1E9}\u{1F1EA}",
        "+49 .. ... ...",
        "Germany",
        "Europe",
        "Western Europe",
    ),
    (
        "+233",
        "\u{1F1EC}\u{1F1ED}",
        "+233 ... ....",
        "Ghana",
        "Africa",
        "Western Africa",
    ),
    (
        "+350",
        "\u{1F1EC}\u{1F1EE}",
        "+350 ... ....",
        "Gibraltar",
        "Europe",
        "Southern Europe",
    ),
    (
        "+30",
        "\u{1F1EC}\u{1F1F7}",
        "+30 .. ... ....",
        "Greece",
        "Europe",
        "Southern Europe",
    ),
    (
        "+299",
        "\u{1F1EC}\u{1F1F1}",
        "+299 ... ....",
        "Greenland",
        "America",
        "Northern America",
    ),
    (
        "+1473",
        "\u{1F1EC}\u{1F1E9}",
        "+1473 ... ....",
        "Grenada",
        "America",
        "Caribbean",
    ),
    (
        "+590",
        "\u{1F1EC}\u{1F1F5}",
        "+590 ... ....",
        "Guadeloupe",
        "America",
        "Caribbean",
    ),
    (
        "+1671",
        "\u{1F1EC}\u{1F1FA}",
        "+1671 ... ....",
        "Guam",
        "Oceania",
        "Micronesia",
    ),
    (
        "+502",
        "\u{1F1EC}\u{1F1F9}",
        "+502 ... ....",
        "Guatemala",
        "America",
        "Central America",
    ),
    (
        "+44",
        "\u{1F1EC}\u{1F1EC}",
        "+44 .. .... ..",
        "Guernsey",
        "Europe",
        "Northern Europe",
    ),
    (
        "+224",
        "\u{1F1EC}\u{1F1F3}",
        "+224 ... ....",
        "Guinea",
        "Africa",
        "Western Africa",
    ),
    (
        "+245",
        "\u{1F1EC}\u{1F1FC}",
        "+245 ... ....",
        "Guinea-Bissau",
        "Africa",
        "Western Africa",
    ),
    (
        "+592",
        "\u{1F1EC}\u{1F1FE}",
        "+592 ... ....",
        "Guyana",
        "America",
        "South America",
    ),
    (
        "+509",
        "\u{1F1ED}\u{1F1F9}",
        "+509 ... ....",
        "Haiti",
        "America",
        "Caribbean",
    ),
    (
        "+504",
        "\u{1F1ED}\u{1F1F3}",
        "+504 ... ....",
        "Honduras",
        "America",
        "Central America",
    ),
    (
        "+852",
        "\u{1F1ED}\u{1F1F0}",
        "+852 ... ....",
        "Hong Kong",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+36",
        "\u{1F1ED}\u{1F1FA}",
        "+36 .. .......",
        "Hungary",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+354",
        "\u{1F1EE}\u{1F1F8}",
        "+354 ... ....",
        "Iceland",
        "Europe",
        "Northern Europe",
    ),
    (
        "+91",
        "\u{1F1EE}\u{1F1F3}",
        "+91 .. ... ....",
        "India",
        "Asia",
        "Southern Asia",
    ),
    (
        "+62",
        "\u{1F1EE}\u{1F1E9}",
        "+62 .. .......",
        "Indonesia",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+98",
        "\u{1F1EE}\u{1F1F7}",
        "+98 .. .... ...",
        "Iran",
        "Asia",
        "Southern Asia",
    ),
    (
        "+964",
        "\u{1F1EE}\u{1F1F6}",
        "+964 ... ....",
        "Iraq",
        "Asia",
        "Western Asia",
    ),
    (
        "+353",
        "\u{1F1EE}\u{1F1EA}",
        "+353 ... ....",
        "Ireland",
        "Europe",
        "Northern Europe",
    ),
    (
        "+44",
        "\u{1F1EE}\u{1F1F2}",
        "+44 .. .... ..",
        "Isle of Man",
        "Europe",
        "Northern Europe",
    ),
    (
        "+972",
        "\u{1F1EE}\u{1F1F1}",
        "+972 ... ....",
        "Israel",
        "Asia",
        "Western Asia",
    ),
    (
        "+39",
        "\u{1F1EE}\u{1F1F9}",
        "+39 .. ... ....",
        "Italy",
        "Europe",
        "Southern Europe",
    ),
    (
        "+1876",
        "\u{1F1EF}\u{1F1F2}",
        "+1876 ... ....",
        "Jamaica",
        "America",
        "Caribbean",
    ),
    (
        "+81",
        "\u{1F1EF}\u{1F1F5}",
        "+81 .. .... ....",
        "Japan",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+44",
        "\u{1F1EF}\u{1F1EA}",
        "+44 .. .... ..",
        "Jersey",
        "Europe",
        "Northern Europe",
    ),
    (
        "+962",
        "\u{1F1EF}\u{1F1F4}",
        "+962 ... ....",
        "Jordan",
        "Asia",
        "Western Asia",
    ),
    (
        "+7",
        "\u{1F1F0}\u{1F1FF}",
        "+7 .. ... ......",
        "Kazakhstan",
        "Asia",
        "Central Asia",
    ),
    (
        "+254",
        "\u{1F1F0}\u{1F1EA}",
        "+254 ... ....",
        "Kenya",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+686",
        "\u{1F1F0}\u{1F1EE}",
        "+686 ... ....",
        "Kiribati",
        "Oceania",
        "Micronesia",
    ),
    (
        "+850",
        "\u{1F1F0}\u{1F1F5}",
        "+850 ... ....",
        "North Korea",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+82",
        "\u{1F1F0}\u{1F1F7}",
        "+82 .. ... ....",
        "South Korea",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+383",
        "\u{1F1FD}\u{1F1F0}",
        "+383 ... ....",
        "Kosovo",
        "Europe",
        "Southern Europe",
    ),
    (
        "+965",
        "\u{1F1F0}\u{1F1FC}",
        "+965 ... ....",
        "Kuwait",
        "Asia",
        "Western Asia",
    ),
    (
        "+996",
        "\u{1F1F0}\u{1F1EC}",
        "+996 ... ....",
        "Kyrgyzstan",
        "Asia",
        "Central Asia",
    ),
    (
        "+856",
        "\u{1F1F1}\u{1F1E6}",
        "+856 ... ....",
        "Laos",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+371",
        "\u{1F1F1}\u{1F1FB}",
        "+371 ... ....",
        "Latvia",
        "Europe",
        "Northern Europe",
    ),
    (
        "+961",
        "\u{1F1F1}\u{1F1E7}",
        "+961 ... ....",
        "Lebanon",
        "Asia",
        "Western Asia",
    ),
    (
        "+266",
        "\u{1F1F1}\u{1F1F8}",
        "+266 ... ....",
        "Lesotho",
        "Africa",
        "Southern Africa",
    ),
    (
        "+231",
        "\u{1F1F1}\u{1F1F7}",
        "+231 ... ....",
        "Liberia",
        "Africa",
        "Western Africa",
    ),
    (
        "+218",
        "\u{1F1F1}\u{1F1FE}",
        "+218 ... ....",
        "Libya",
        "Africa",
        "Northern Africa",
    ),
    (
        "+423",
        "\u{1F1F1}\u{1F1EE}",
        "+423 ... ....",
        "Liechtenstein",
        "Europe",
        "Western Europe",
    ),
    (
        "+370",
        "\u{1F1F1}\u{1F1F9}",
        "+370 ... ....",
        "Lithuania",
        "Europe",
        "Northern Europe",
    ),
    (
        "+352",
        "\u{1F1F1}\u{1F1FA}",
        "+352 ... ....",
        "Luxembourg",
        "Europe",
        "Western Europe",
    ),
    (
        "+853",
        "\u{1F1F2}\u{1F1F4}",
        "+853 ... ....",
        "Macau",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+389",
        "\u{1F1F2}\u{1F1F0}",
        "+389 ... ....",
        "North Macedonia",
        "Europe",
        "Southern Europe",
    ),
    (
        "+261",
        "\u{1F1F2}\u{1F1EC}",
        "+261 ... ....",
        "Madagascar",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+265",
        "\u{1F1F2}\u{1F1FC}",
        "+265 ... ....",
        "Malawi",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+60",
        "\u{1F1F2}\u{1F1FE}",
        "+60 .. ... ...",
        "Malaysia",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+960",
        "\u{1F1F2}\u{1F1FB}",
        "+960 ... ....",
        "Maldives",
        "Asia",
        "Southern Asia",
    ),
    (
        "+223",
        "\u{1F1F2}\u{1F1F1}",
        "+223 ... ....",
        "Mali",
        "Africa",
        "Western Africa",
    ),
    (
        "+356",
        "\u{1F1F2}\u{1F1F9}",
        "+356 ... ....",
        "Malta",
        "Europe",
        "Southern Europe",
    ),
    (
        "+692",
        "\u{1F1F2}\u{1F1ED}",
        "+692 ... ....",
        "Marshall Islands",
        "Oceania",
        "Micronesia",
    ),
    (
        "+596",
        "\u{1F1F2}\u{1F1F6}",
        "+596 ... ....",
        "Martinique",
        "America",
        "Caribbean",
    ),
    (
        "+222",
        "\u{1F1F2}\u{1F1F7}",
        "+222 ... ....",
        "Mauritania",
        "Africa",
        "Western Africa",
    ),
    (
        "+230",
        "\u{1F1F2}\u{1F1FA}",
        "+230 ... ....",
        "Mauritius",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+262",
        "\u{1F1FE}\u{1F1F9}",
        "+262 ... ....",
        "Mayotte",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+52",
        "\u{1F1F2}\u{1F1FD}",
        "+52 .. .... ....",
        "Mexico",
        "America",
        "Central America",
    ),
    (
        "+691",
        "\u{1F1EB}\u{1F1F2}",
        "+691 ... ....",
        "Micronesia",
        "Oceania",
        "Micronesia",
    ),
    (
        "+373",
        "\u{1F1F2}\u{1F1E9}",
        "+373 ... ....",
        "Moldova",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+377",
        "\u{1F1F2}\u{1F1E8}",
        "+377 ... ....",
        "Monaco",
        "Europe",
        "Western Europe",
    ),
    (
        "+976",
        "\u{1F1F2}\u{1F1F3}",
        "+976 ... ....",
        "Mongolia",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+382",
        "\u{1F1F2}\u{1F1EA}",
        "+382 ... ....",
        "Montenegro",
        "Europe",
        "Southern Europe",
    ),
    (
        "+1664",
        "\u{1F1F2}\u{1F1F8}",
        "+1664 ... ....",
        "Montserrat",
        "America",
        "Caribbean",
    ),
    (
        "+212",
        "\u{1F1EA}\u{1F1ED}",
        "+212 ... ....",
        "Morocco",
        "Africa",
        "Northern Africa",
    ),
    (
        "+258",
        "\u{1F1F2}\u{1F1FF}",
        "+258 ... ....",
        "Mozambique",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+95",
        "\u{1F1F2}\u{1F1F2}",
        "+95 .. .... ....",
        "Myanmar",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+264",
        "\u{1F1F3}\u{1F1E6}",
        "+264 ... ....",
        "Namibia",
        "Africa",
        "Southern Africa",
    ),
    (
        "+674",
        "\u{1F1F3}\u{1F1F7}",
        "+674 ... ....",
        "Nauru",
        "Oceania",
        "Micronesia",
    ),
    (
        "+977",
        "\u{1F1F3}\u{1F1F5}",
        "+977 ... ....",
        "Nepal",
        "Asia",
        "Southern Asia",
    ),
    (
        "+31",
        "\u{1F1F3}\u{1F1F1}",
        "+31 .. ... ..",
        "Netherlands",
        "Europe",
        "Western Europe",
    ),
    (
        "+599",
        "\u{1F1E7}\u{1F1F6}",
        "+599 ... ....",
        "Netherlands Antilles",
        "America",
        "Caribbean",
    ),
    (
        "+687",
        "\u{1F1F3}\u{1F1E8}",
        "+687 ... ....",
        "New Caledonia",
        "Oceania",
        "Melanesia",
    ),
    (
        "+64",
        "\u{1F1F3}\u{1F1FF}",
        "+64 .. ... ....",
        "New Zealand",
        "Oceania",
        "Australia",
    ),
    (
        "+505",
        "\u{1F1F3}\u{1F1EE}",
        "+505 ... ....",
        "Nicaragua",
        "America",
        "Central America",
    ),
    (
        "+227",
        "\u{1F1F3}\u{1F1EA}",
        "+227 ... ....",
        "Niger",
        "Africa",
        "Western Africa",
    ),
    (
        "+234",
        "\u{1F1F3}\u{1F1EC}",
        "+234 ... ....",
        "Nigeria",
        "Africa",
        "Western Africa",
    ),
    (
        "+683",
        "\u{1F1F3}\u{1F1FA}",
        "+683 ... ....",
        "Niue",
        "Oceania",
        "Polynesia",
    ),
    (
        "+672",
        "\u{1F1F3}\u{1F1EB}",
        "+672 ... ....",
        "Norfolk Island",
        "Oceania",
        "Australia",
    ),
    (
        "+1670",
        "\u{1F1F2}\u{1F1F5}",
        "+1670 ... ....",
        "Northern Mariana Islands",
        "Oceania",
        "Micronesia",
    ),
    (
        "+47",
        "\u{1F1F3}\u{1F1F4}",
        "+47 .. ... ....",
        "Norway",
        "Europe",
        "Northern Europe",
    ),
    (
        "+968",
        "\u{1F1F4}\u{1F1F2}",
        "+968 ... ....",
        "Oman",
        "Asia",
        "Western Asia",
    ),
    (
        "+92",
        "\u{1F1F5}\u{1F1F0}",
        "+92 .. ... ..",
        "Pakistan",
        "Asia",
        "Southern Asia",
    ),
    (
        "+680",
        "\u{1F1F5}\u{1F1FC}",
        "+680 ... ....",
        "Palau",
        "Oceania",
        "Micronesia",
    ),
    (
        "+970",
        "\u{1F1F5}\u{1F1F8}",
        "+970 ... ....",
        "Palestinian Territories",
        "Asia",
        "Western Asia",
    ),
    (
        "+507",
        "\u{1F1F5}\u{1F1E6}",
        "+507 ... ....",
        "Panama",
        "America",
        "Central America",
    ),
    (
        "+675",
        "\u{1F1F5}\u{1F1EC}",
        "+675 ... ....",
        "Papua New Guinea",
        "Oceania",
        "Melanesia",
    ),
    (
        "+595",
        "\u{1F1F5}\u{1F1FE}",
        "+595 ... ....",
        "Paraguay",
        "South America",
        "South America",
    ),
    (
        "+51",
        "\u{1F1F5}\u{1F1EA}",
        "+51 .. .... ....",
        "Peru",
        "America",
        "South America",
    ),
    (
        "+63",
        "\u{1F1F5}\u{1F1ED}",
        "+63 .. ... ....",
        "Philippines",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+48",
        "\u{1F1F5}\u{1F1F1}",
        "+48 .. .... ....",
        "Poland",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+351",
        "\u{1F1F5}\u{1F1F9}",
        "+351 ... ....",
        "Portugal",
        "Europe",
        "Southern Europe",
    ),
    (
        "+1",
        "\u{1F1F5}\u{1F1F7}",
        "+1 ... ... ....",
        "Puerto Rico",
        "America",
        "Caribbean",
    ),
    (
        "+974",
        "\u{1F1F6}\u{1F1E6}",
        "+974 ... ....",
        "Qatar",
        "Asia",
        "Western Asia",
    ),
    (
        "+262",
        "\u{1F1F7}\u{1F1EA}",
        "+262 ... ....",
        "R\u{E9}union",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+40",
        "\u{1F1F7}\u{1F1F4}",
        "+40 .. .... ....",
        "Romania",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+7",
        "\u{1F1F7}\u{1F1FA}",
        "+7 .. ... ......",
        "Russia",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+250",
        "\u{1F1F7}\u{1F1FC}",
        "+250 ... ....",
        "Rwanda",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+290",
        "\u{1F1F8}\u{1F1ED}",
        "+290 ... ....",
        "Saint Helena",
        "Africa",
        "Atlantic",
    ),
    (
        "+1869",
        "\u{1F1F0}\u{1F1F3}",
        "+1869 ... ....",
        "Saint Kitts and Nevis",
        "America",
        "Caribbean",
    ),
    (
        "+1758",
        "\u{1F1F1}\u{1F1E8}",
        "+1758 ... ....",
        "Saint Lucia",
        "America",
        "Caribbean",
    ),
    (
        "+590",
        "\u{1F1EC}\u{1F1F5}",
        "+590 ... ....",
        "Saint Pierre and Miquelon",
        "America",
        "Northern America",
    ),
    (
        "+1784",
        "\u{1F1FB}\u{1F1E8}",
        "+1784 ... ....",
        "Saint Vincent and the Grenadines",
        "America",
        "Caribbean",
    ),
    (
        "+685",
        "\u{1F1FC}\u{1F1F8}",
        "+685 ... ....",
        "Samoa",
        "Oceania",
        "Polynesia",
    ),
    (
        "+378",
        "\u{1F1F8}\u{1F1F2}",
        "+378 ... ....",
        "San Marino",
        "Europe",
        "Southern Europe",
    ),
    (
        "+239",
        "\u{1F1F8}\u{1F1F9}",
        "+239 ... ....",
        "S\u{E3}o Tom\u{E9} and Pr\u{ED}ncipe",
        "Africa",
        "Middle Africa",
    ),
    (
        "+966",
        "\u{1F1F8}\u{1F1E6}",
        "+966 ... ....",
        "Saudi Arabia",
        "Asia",
        "Western Asia",
    ),
    (
        "+221",
        "\u{1F1F8}\u{1F1F3}",
        "+221 ... ....",
        "Senegal",
        "Africa",
        "Western Africa",
    ),
    (
        "+381",
        "\u{1F1F7}\u{1F1F8}",
        "+381 ... ....",
        "Serbia",
        "Europe",
        "Southern Europe",
    ),
    (
        "+248",
        "\u{1F1F8}\u{1F1E8}",
        "+248 ... ....",
        "Seychelles",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+232",
        "\u{1F1F8}\u{1F1F1}",
        "+232 ... ....",
        "Sierra Leone",
        "Africa",
        "Western Africa",
    ),
    (
        "+65",
        "\u{1F1F8}\u{1F1EC}",
        "+65 ... ....",
        "Singapore",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+1721",
        "\u{1F1F8}\u{1F1FD}",
        "+1721 ... ....",
        "Sint Maarten",
        "America",
        "Caribbean",
    ),
    (
        "+421",
        "\u{1F1F8}\u{1F1F0}",
        "+421 ... ....",
        "Slovakia",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+386",
        "\u{1F1F8}\u{1F1EE}",
        "+386 ... ....",
        "Slovenia",
        "Europe",
        "Southern Europe",
    ),
    (
        "+677",
        "\u{1F1F8}\u{1F1E7}",
        "+677 ... ....",
        "Solomon Islands",
        "Oceania",
        "Melanesia",
    ),
    (
        "+252",
        "\u{1F1F8}\u{1F1F4}",
        "+252 ... ....",
        "Somalia",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+27",
        "\u{1F1FF}\u{1F1E6}",
        "+27 .. .... ....",
        "South Africa",
        "Africa",
        "Southern Africa",
    ),
    (
        "+211",
        "\u{1F1F8}\u{1F1F8}",
        "+211 ... ....",
        "South Sudan",
        "Africa",
        "Middle Africa",
    ),
    (
        "+34",
        "\u{1F1EA}\u{1F1F8}",
        "+34 .. ... ....",
        "Spain",
        "Europe",
        "Southern Europe",
    ),
    (
        "+94",
        "\u{1F1F1}\u{1F1F0}",
        "+94 .. ... ....",
        "Sri Lanka",
        "Asia",
        "Southern Asia",
    ),
    (
        "+249",
        "\u{1F1F8}\u{1F1E9}",
        "+249 ... ....",
        "Sudan",
        "Africa",
        "Northern Africa",
    ),
    (
        "+597",
        "\u{1F1F8}\u{1F1F7}",
        "+597 ... ....",
        "Suriname",
        "America",
        "South America",
    ),
    (
        "+47",
        "\u{1F1F8}\u{1F1EF}",
        "+47 .. ... ....",
        "Svalbard and Jan Mayen",
        "Europe",
        "Northern Europe",
    ),
    (
        "+268",
        "\u{1F1F8}\u{1F1FF}",
        "+268 ... ....",
        "Swaziland",
        "Africa",
        "Southern Africa",
    ),
    (
        "+46",
        "\u{1F1F8}\u{1F1EA}",
        "+46 .. ... ....",
        "Sweden",
        "Europe",
        "Northern Europe",
    ),
    (
        "+41",
        "\u{1F1E8}\u{1F1ED}",
        "+41 .. ... ....",
        "Switzerland",
        "Europe",
        "Western Europe",
    ),
    (
        "+963",
        "\u{1F1F8}\u{1F1FE}",
        "+963 ... ....",
        "Syria",
        "Asia",
        "Western Asia",
    ),
    (
        "+886",
        "\u{1F1F9}\u{1F1FC}",
        "+886 ... ....",
        "Taiwan",
        "Asia",
        "Eastern Asia",
    ),
    (
        "+992",
        "\u{1F1F9}\u{1F1EF}",
        "+992 ... ....",
        "Tajikistan",
        "Asia",
        "Central Asia",
    ),
    (
        "+255",
        "\u{1F1F9}\u{1F1FF}",
        "+255 ... ....",
        "Tanzania",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+66",
        "\u{1F1F9}\u{1F1ED}",
        "+66 .. ... ....",
        "Thailand",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+670",
        "\u{1F1F9}\u{1F1F1}",
        "+670 ... ....",
        "Timor-Leste",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+228",
        "\u{1F1F9}\u{1F1EC}",
        "+228 ... ....",
        "Togo",
        "Africa",
        "Western Africa",
    ),
    (
        "+690",
        "\u{1F1F9}\u{1F1F0}",
        "+690 ... ....",
        "Tokelau",
        "Oceania",
        "Polynesia",
    ),
    (
        "+676",
        "\u{1F1F9}\u{1F1F4}",
        "+676 ... ....",
        "Tonga",
        "Oceania",
        "Polynesia",
    ),
    (
        "+1868",
        "\u{1F1F9}\u{1F1F9}",
        "+1868 ... ....",
        "Trinidad and Tobago",
        "America",
        "Caribbean",
    ),
    (
        "+216",
        "\u{1F1F9}\u{1F1F3}",
        "+216 ... ....",
        "Tunisia",
        "Africa",
        "Northern Africa",
    ),
    (
        "+90",
        "\u{1F1F9}\u{1F1F7}",
        "+90 .. ... ....",
        "Turkey",
        "Europe",
        "Western Asia",
    ),
    (
        "+993",
        "\u{1F1F9}\u{1F1F2}",
        "+993 ... ....",
        "Turkmenistan",
        "Asia",
        "Central Asia",
    ),
    (
        "+1649",
        "\u{1F1F9}\u{1F1E8}",
        "+1649 ... ....",
        "Turks and Caicos Islands",
        "America",
        "Caribbean",
    ),
    (
        "+688",
        "\u{1F1F9}\u{1F1FB}",
        "+688 ... ....",
        "Tuvalu",
        "Oceania",
        "Polynesia",
    ),
    (
        "+256",
        "\u{1F1FA}\u{1F1EC}",
        "+256 ... ....",
        "Uganda",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+380",
        "\u{1F1FA}\u{1F1E6}",
        "+380 ... ....",
        "Ukraine",
        "Europe",
        "Eastern Europe",
    ),
    (
        "+971",
        "\u{1F1E6}\u{1F1EA}",
        "+971 ... ....",
        "United Arab Emirates",
        "Asia",
        "Western Asia",
    ),
    (
        "+44",
        "\u{1F1EC}\u{1F1E7}",
        "+44 .. .... ..",
        "United Kingdom",
        "Europe",
        "Northern Europe",
    ),
    (
        "+1",
        "\u{1F1FA}\u{1F1F8}",
        "+1 ... ... ....",
        "United States",
        "America",
        "Northern America",
    ),
    (
        "+598",
        "\u{1F1FA}\u{1F1FE}",
        "+598 ... ....",
        "Uruguay",
        "America",
        "South America",
    ),
    (
        "+998",
        "\u{1F1FA}\u{1F1FF}",
        "+998 ... ....",
        "Uzbekistan",
        "Asia",
        "Central Asia",
    ),
    (
        "+678",
        "\u{1F1FB}\u{1F1FA}",
        "+678 ... ....",
        "Vanuatu",
        "Oceania",
        "Melanesia",
    ),
    (
        "+39",
        "\u{1F1FB}\u{1F1E6}",
        "+39 .. ... ....",
        "Vatican City",
        "Europe",
        "Southern Europe",
    ),
    (
        "+58",
        "\u{1F1FB}\u{1F1EA}",
        "+58 .. .... ....",
        "Venezuela",
        "America",
        "South America",
    ),
    (
        "+84",
        "\u{1F1FB}\u{1F1F3}",
        "+84 .. .... ....",
        "Vietnam",
        "Asia",
        "South-Eastern Asia",
    ),
    (
        "+1284",
        "\u{1F1FB}\u{1F1EC}",
        "+1284 ... ....",
        "Virgin Islands (UK)",
        "America",
        "Caribbean",
    ),
    (
        "+1340",
        "\u{1F1FB}\u{1F1EE}",
        "+1340 ... ....",
        "Virgin Islands (US)",
        "America",
        "Caribbean",
    ),
    (
        "+681",
        "\u{1F1FC}\u{1F1EB}",
        "+681 ... ....",
        "Wallis and Futuna",
        "Oceania",
        "Polynesia",
    ),
    (
        "+212",
        "\u{1F1EA}\u{1F1ED}",
        "+212 ... ....",
        "Western Sahara",
        "Africa",
        "Northern Africa",
    ),
    (
        "+967",
        "\u{1F1FE}\u{1F1EA}",
        "+967 ... ....",
        "Yemen",
        "Asia",
        "Western Asia",
    ),
    (
        "+260",
        "\u{1F1FF}\u{1F1F2}",
        "+260 ... ....",
        "Zambia",
        "Africa",
        "Eastern Africa",
    ),
    (
        "+263",
        "\u{1F1FF}\u{1F1FC}",
        "+263 ... ....",
        "Zimbabwe",
        "Africa",
        "Eastern Africa",
    ),
];
